baseURL = 'https://www.datafromlopes.com/'
languageCode = 'en-us'
title = 'Diego Lopes | Data Engineer & AI Researcher'
theme = 'datafromlopes'

enableRobotsTXT = true
pagination.pagerSize = 6
pagination.path = "page"

[params]
  name = "Diego Lopes"
  description = 'MSc in Computer Science @ IME-USP'
  tagline = "Data Engineer & Researcher"
  location = "São Paulo, Brazil"

  [params.social]
    linkedin = "https://www.linkedin.com/in/datafromlopes"
    github   = "https://github.com/datafromlopes"
    twitter  = "https://x.com/datafromlopes"
    orcid  = "https://orcid.org/0000-0002-5130-3728"
    kaggle = "https://www.kaggle.com/datafromlopes"
    email    = "diego.lopes@datafromlopes.com"

[taxonomies]
  tag = "tags"
  category = "categories"

[menus]
  [[menus.main]]
    name = 'About Me'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects/'
    weight = 20

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog/'
    weight = 40


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
